apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: helm
spec:
  targetNamespace: ingress-nginx
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.7.0
  values:
    controller:
      kind: DaemonSet
      service:
        type: NodePort
        nodePorts:
          http: 30080
    defaultBackend:
      enabled: true